services:
  mysql-hotel-service:
    image: 'mysql:latest'
    container_name: container_mysql_hotel
    ports:
      - 3306:3306
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=hotel_db'
      - 'MYSQL_USER=testuser'
      - 'MYSQL_PASSWORD=passer'
  phpmyadmin-hotel-service:
    image: phpmyadmin/phpmyadmin:latest
    container_name: container_phpmyadmin_hotel
    ports:
      - 8085:80
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'PMA_HOST=mysql-hotel-service'
      - 'PMA_USER=testuser'
    depends_on:
      - mysql-hotel-service
    restart: unless-stopped